### ISSUE TITLE
error ?

### ISSUE THREAD

**Issue by xpsaeed** [unlimiteeed/x-ui-Craker#1]
hi
dont work !

Traceback (most recent call last):
  File "/home/kali/Downloads/x-ui-Craker/x-ui.py", line 3, in <module>
    from src import banners
  File "/home/kali/Downloads/x-ui-Craker/src/__init__.py", line 1, in <module>
    from .banner import banners
  File "/home/kali/Downloads/x-ui-Craker/src/banner.py", line 3, in <module>
    from colorama import Fore , Back , init , just_fix_windows_console
ImportError: cannot import name 'just_fix_windows_console' from 'colorama' (/usr/lib/python3/dist-packages/colorama/__init__.py)

**Comment by unlimiteeed** [comment]
Hi I will check it but you can open issues on github

**Comment by unlimiteeed** [comment]
Hi, I will check it also im going to make a new version of it on the golang soon.

**Comment by unlimiteeed** [comment]
Hi i review the problem and its work fine for me on my ubuntue try to use it on a diffrent os 
![image](https://github.com/user-attachments/assets/8c385231-4c02-4e2e-b103-79ec9d4a931b)
![image](https://github.com/user-attachments/assets/942b3cb6-c581-4209-bea7-84156b242d01)
